// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2HiL0k2V_QR_TKuKErwKtmMCMFPZL8qU',
    appId: '1:847796568416:android:91ea9174cf4bb567181e05',
    messagingSenderId: '847796568416',
    projectId: 'uber-clone-d9c7d',
    databaseURL: 'https://uber-clone-d9c7d-default-rtdb.firebaseio.com',
    storageBucket: 'uber-clone-d9c7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo0qFK4hIbmNDI9aTVacN5LRnNz6e4hok',
    appId: '1:847796568416:ios:4a7ba7e284a8b293181e05',
    messagingSenderId: '847796568416',
    projectId: 'uber-clone-d9c7d',
    databaseURL: 'https://uber-clone-d9c7d-default-rtdb.firebaseio.com',
    storageBucket: 'uber-clone-d9c7d.appspot.com',
    iosClientId: '847796568416-0ong139ql8jked7gps6s810r4u3o4a5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberDriverApp',
  );
}
